### ISSUE TITLE
Amap

### ISSUE THREAD

**Issue by BaffledJimmy** [No-0Peration/Recon#6]
Hi,

Would it be worth building in amap to Recon? eg whichever ports that Nmap can't detect you can sometimes get a bit more info from it.

I had a quick look to see if it would be easy enough but I've only just started learning Python and finding it a bit confusing.

Suggested command:
AMap -bUqv -C 5 <host IP> <port number>

Additional commands that could be useful
-i FILE is Nmap file to read ports from
-b is print ASCII
-U is don’t dump unrecognised responses
-o FILE is output file

More info:
https://tools.kali.org/information-gathering/amap

:)

**Comment by No-0Peration** [comment]
Hi, nmap is realy the base of this project, the complete reconmodules act on parsing the first NMAP portscans. It would be a huge rewrite to replace nmap for amap. Since i'm currently pretty busy this is probably not going to happen soon, but maybe you can fork the project to try replaceing the nmap part. :)

**Comment by BaffledJimmy** [comment]
Hi,

No I just meant for ports that come back as unrecognised from NMap.

eg its on p80 but doesn't respond to http requests so amap would send a lot
of different types of triggers until the application responded and it could
work out what it was.

Not a great explanation sorry!  It would be a module called by the main
reconscript and you can supply amap with an input list (eg from nmap)
